#server:
#  port: 8761
#
#spring:
#  application:
#    name: eureka
#
#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#    client:
#      serviceUrl:
#        defaultZone: ${EUREKA_SERVER_ADDRESS}
#      register-with-eureka: true
#      fetch-registry: false
server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: false